[package]
name = "engine"
version = "0.1.0"
authors = ["sombrastudios <nils.martel@concepts-system.com>"]

[dependencies]
nom = "5.0.1"                # A byte-oriented, zero-copy, parser combinators library
